name: chore_champion
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  provider: ^6.1.1
  forest_logger: ^1.1.0
  chopper: ^7.1.1
  chopper_generator: ^7.1.1
  url_launcher: ^6.2.4
  fluttertoast: ^8.2.4
  flutter_localization: ^0.2.0
  freezed: ^2.4.7
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  form_builder_validators: ^9.1.0
  flutter_svg: ^2.0.9
  package_info_plus: ^5.0.1
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.3.10
  device_info_plus: ^9.1.2
  connectivity_plus: ^5.0.2
  translatron: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
